export enum Roles {
    ORDER = 'order',
    ORDER_CREATE = 'order_create',
    ORDER_UPDATE = 'order_update',
    ORDER_CANCEL = 'order_cancel',
    ORDER_POSITION = 'order_position',

    ORDER_STATE = 'order_state',
    ORDER_STATE_CREATE = 'order_state_create',
    ORDER_STATE_UPDATE = 'order_state_update',
    ORDER_STATE_DELETE = 'order_state_delete',

    SALE = 'sale',
    SALE_CREATE = 'sale_create',
    SALE_UPDATE = 'sale_update',
    SALE_CANCEL = 'sale_cancel',
    SALE_APPROVE = 'sale_approve',
    SALE_COMPLETE = 'sale_complete',
    SALE_REFUND = 'sale_refund',

    WAREHOUSE = 'warehouse',
    WAREHOUSE_CREATE = 'warehouse_create',
    WAREHOUSE_UPDATE = 'warehouse_update',
    WAREHOUSE_DELETE = 'warehouse_delete',

    CATEGORY = 'category',
    CATEGORY_CREATE = 'category_create',
    CATEGORY_UPDATE = 'category_update',
    CATEGORY_DELETE = 'category_delete',

    PRODUCT = 'product',
    PRODUCT_CREATE = 'product_create',
    PRODUCT_UPDATE = 'product_update',
    PRODUCT_DELETE = 'product_delete',

    PRICE = 'price',
    PRICE_CREATE = 'price_create',
    PRICE_UPDATE = 'price_update',
    PRICE_DELETE = 'price_delete',

    PRODUCT_WAREHOUSE = 'product_warehouse',
    PRODUCT_COST = 'product_cost',
    ORGANIZATION_STOCK = 'organization_stock',
    WAREHOUSE_STOCK = 'warehouse_stock',
    SECTION_STOCK = 'section_stock',
    CATEGORY_STOCK = 'category_stock',
    STOCK_COST_VISIBLE = 'stock_cost_visible',

    INVENTORY = 'inventory',
    INVENTORY_CREATE = 'inventory_create',
    INVENTORY_COUNT = 'inventory_count',
    INVENTORY_COMPLETE = 'inventory_complete',
    INVENTORY_CANCEL = 'inventory_cancel',

    WRITE_OFF = 'write_off',
    WRITE_OFF_CREATE = 'write_off_create',
    WRITE_OFF_CANCEL = 'write_off_cancel',

    INNER_TRANSFER = 'inner_transfer',
    INNER_TRANSFER_CREATE = 'inner_transfer_create',
    INNER_TRANSFER_CANCEL = 'inner_transfer_cancel',

    ORGANIZATIONAL_TRANSFER = 'organizational_transfer',
    ORGANIZATIONAL_TRANSFER_CREATE = 'organizational_transfer_create',
    ORGANIZATIONAL_TRANSFER_CANCEL = 'organizational_transfer_cancel',

    SECTION_TRANSFER = 'section_transfer',

    PRODUCTION = 'production',
    PRODUCTION_COMPLETE = 'production_complete',
    PRODUCTION_SALARY = 'production_salary',
    PRODUCTION_SETTINGS = 'production_settings',
    PRODUCTION_HISTORY = 'production_history',

    PRODUCTION_STATE = 'production_state',
    PRODUCTION_STATE_CREATE = 'production_state_create',
    PRODUCTION_STATE_UPDATE = 'production_state_update',
    PRODUCTION_STATE_DELETE = 'production_state_delete',

    CASHBOX = 'cashbox',
    CASHBOX_CREATE = 'cashbox_create',
    CASHBOX_UPDATE = 'cashbox_update',
    CASHBOX_DELETE = 'cashbox_delete',
    CASHBOX_SET_BALANCE = 'cashbox_set_balance',

    TRANSACTION = 'transaction',
    TRANSACTION_INCOME = 'transaction_income',
    TRANSACTION_EXPENSE = 'transaction_expense',
    TRANSACTION_CANCEL = 'transaction_cancel',
    TRANSACTION_TRANSFER = 'transaction_transfer',
    TRANSACTION_EXCHANGE = 'transaction_exchange',
    TRANSACTION_EXCHANGE_METHOD = 'transaction_exchange_method',
    TRANSACTION_DATE_CHANGE = 'transaction_date_change',

    CURRENCY = 'currency',
    CURRENCY_CREATE = 'currency_create',
    CURRENCY_UPDATE = 'currency_update',
    CURRENCY_DELETE = 'currency_delete',

    PAYMENT_METHOD = 'payment_method',
    PAYMENT_METHOD_CREATE = 'payment_method_create',
    PAYMENT_METHOD_UPDATE = 'payment_method_update',
    PAYMENT_METHOD_DELETE = 'payment_method_delete',

    TRANSACTION_TYPE = 'transaction_type',
    TRANSACTION_TYPE_CREATE = 'transaction_type_create',
    TRANSACTION_TYPE_UPDATE = 'transaction_type_update',
    TRANSACTION_TYPE_DELETE = 'transaction_type_delete',

    SUPPLIER = 'supplier',
    SUPPLIER_CREATE = 'supplier_create',
    SUPPLIER_UPDATE = 'supplier_update',
    SUPPLIER_DELETE = 'supplier_delete',
    SUPPLIER_SET_BALANCE = 'supplier_set_balance',

    PURCHASE = 'purchase',
    PURCHASE_CREATE = 'purchase_create',
    PURCHASE_UPDATE = 'purchase_update',
    PURCHASE_CANCEL = 'purchase_cancel',

    REFUND = 'purchase',
    REFUND_CREATE = 'purchase_create',
    REFUND_UPDATE = 'purchase_update',
    REFUND_CANCEL = 'purchase_cancel',

    CUSTOMER = 'customer',
    CUSTOMER_CREATE = 'customer_create',
    CUSTOMER_UPDATE = 'customer_update',
    CUSTOMER_DELETE = 'customer_delete',
    CUSTOMER_DEBT_LIMIT = 'customer_debt_limit',
    CUSTOMER_ORDER = 'customer_orders',
    CUSTOMER_TRANSACTION = 'customer_transactions',
    CUSTOMER_PRODUCT = 'customer_products',

    ROLE = 'role',
    ROLE_CREATE = 'role_create',
    ROLE_UPDATE = 'role_update',
    ROLE_DELETE = 'role_delete',

    EMPLOYEE = 'employee',
    EMPLOYEE_CREATE = 'employee_create',
    EMPLOYEE_UPDATE = 'employee_update',
    EMPLOYEE_DELETE = 'employee_delete',

    UNIT_OF_MEASURE = 'unit_of_measure',
    UNIT_OF_MEASURE_CREATE = 'unit_of_measure_create',
    UNIT_OF_MEASURE_UPDATE = 'unit_of_measure_update',
    UNIT_OF_MEASURE_DELETE = 'unit_of_measure_delete',

    CUSTOM_FIELD = 'custom_field',
    CUSTOM_FIELD_CREATE = 'custom_field_create',
    CUSTOM_FIELD_UPDATE = 'custom_field_update',
    CUSTOM_FIELD_DELETE = 'custom_field_delete',

    REPORTS = 'reports',
    REPORTS_PRODUCT = 'reports_product',
    REPORTS_CATEGORY = 'reports_category',
    REPORTS_CUSTOMER = 'reports_customer',
    REPORTS_EMPLOYEE = 'reports_employee',
    REPORTS_SALE = 'reports_sale',
    REPORTS_SALE_CUSTOMER = 'reports_sale_customer',
    REPORTS_SALE_WITH_ITEMS = 'reports_sale_with_items',
    REPORTS_PRODUCT_CUSTOMER = 'reports_product_customer',
    REPORTS_CASHFLOW = 'reports_cashflow',
    REPORTS_PRODUCTION = 'reports_production',
    REPORTS_TRANSACTION_CUSTOMER = 'reports_transaction_customer',
    REPORTS_COST_VISIBLE = 'reports_cost_visible',
    REPORTS_PROFIT_VISIBLE = 'reports_profit_visible',

    SET_BALANCE = 'set_balance',
    RECON_ACT = 'recon_act',

    BOX = 'box',
    BOX_CREATE = 'box_create',
    BOX_UPDATE = 'box_update',
    BOX_DELETE = 'box_delete',
}
